// plantasCompletas.js

// Este archivo contiene la información completa y fusionada de las 22 plantas definitivas,
// combinando datos astrológicos con descripciones extendidas y URLs de imagen.

const plantasCompletas = [
  {
    key: "cactus-mani",
    nombre: "Cactus maní",
    signos: ["Aries", "Leo", "Sagitario"],
    vida: ["Creatividad", "Vitalidad"],
    elementos: ["Fuego", "Tierra"],
    niveles: ["Físico", "Emocional"],
    short: "Pequeño, alegre y resistente, con flores amarillas.",
    descripcion: "Representa la alegría simple, la vitalidad y la renovación constante.",
    energia: "alegría, renovación, vitalidad",
    arquetipos: [
      "Un estallido de energía en miniatura, trayendo alegría a cada rincón.",
      "Resistente y vital, te recuerda que la vida florece en los lugares más inesperados.",
      "Guarda en silencio la fuerza que crece sin ser vista.",
      "Resiste con dulzura: tu suavidad es tu escudo.",
      "No necesitas mostrar espinas para proteger tu esencia.",
      "La alegría sencilla multiplica la abundancia.",
      "Expande tu energía como el sol de la mañana.",
      "Cada hoja es un pequeño milagro de perseverancia.",
      "Vitalidad solar, alegría contagiosa.",
      "La ligereza del juego hace más fácil el camino."
    ],
    descripcionExtendida: "La (Echinopsis chamaecereus) es una verdadera delicia para los amantes de las suculentas. Este cactus de tallos delgados y dedos, que parecen cacahuetes, forma densos grupos que se extienden con gracia. Sus suaves espinas apenas se notan, haciendo de él una planta muy amigable al tacto. En primavera y verano, se adorna con una espectacular floración de vibrantes flores de color naranja o rojo intenso, creando un contraste asombroso con sus tallos verdes. Es fácil de cuidar y perfecto para añadir un toque de alegría y color a cualquier espacio.",
    imagenUrl: "fotos/cactus-mani.jpg"
  },
  {
    key: "graptosedum-california-sunset",
    nombre: "Graptosedum California Sunset",
    signos: ["Leo", "Sagitario", "Piscis"],
    vida: ["Transformación", "Belleza"],
    elementos: ["Fuego", "Agua"],
    niveles: ["Emocional", "Espiritual"],
    short: "Cambia de color con el sol, vibrante y hermoso.",
    descripcion: "Simboliza la transformación, la belleza y la adaptación a la luz.",
    energia: "transformación, creatividad, adaptabilidad",
    arquetipos: [
      "Cada matiz de tu ser es una pincelada de un atardecer único.",
      "El sol te pinta de valentía, la luz te muestra tu fuerza.",
      "Los colores de tu alma se despliegan al sol, llenos de vida.",
      "Con la luz adecuada, tus verdaderos colores resplandecen.",
      "El secreto de tu brillo está en tu capacidad de transformarte.",
      "La belleza está en los matices, en las transiciones de la vida.",
      "Deja que el sol pinte tu alma con colores de esperanza.",
      "Tu espíritu se enciende y brilla con cada nueva experiencia.",
      "Un lienzo viviente, pintado por la luz del alma.",
      "La suavidad de tu espíritu se tiñe de mil colores."
    ],
    descripcionExtendida: "El Graptosedum 'California Sunset' es una suculenta híbrida que se destaca por sus hojas carnosas de color verde grisáceo que, bajo una exposición solar intensa, desarrollan hermosos tonos anaranjados, rosados y rojizos, emulando los colores de un atardecer. Sus rosetas crecen en forma compacta y se extienden a medida que la planta madura, creando un tapiz de color. Es resistente, fácil de cuidar y ideal para añadir un toque cálido y vibrante a cualquier colección.",
    imagenUrl: "fotos/graptosedum-california-sunset.jpg"
  },
  {
    key: "huernia",
    nombre: "Huernia",
    signos: ["Escorpio", "Capricornio", "Acuario"],
    vida: ["Resiliencia", "Determinación"],
    elementos: ["Tierra", "Aire"],
    niveles: ["Mental", "Físico"],
    short: "Cactus de flores exóticas y robustez.",
    descripcion: "Representa la resiliencia en la adversidad y la belleza inesperada.",
    energia: "resiliencia, fuerza interior, sorpresa",
    arquetipos: [
      "La flor más hermosa a veces nace de la sombra.",
      "En lo inesperado, encontrarás tu mayor fortaleza y belleza.",
      "Tu singularidad es tu mayor tesoro, no la escondas.",
      "La vida tiene sorpresas que solo el valiente puede descubrir.",
      "Incluso en el silencio, tu fuerza interior florece.",
      "Las apariencias engañan: tu verdadera belleza está en tu esencia.",
      "Sé valiente para mostrar tu verdadera y única flor.",
      "La resiliencia te permite florecer donde menos lo esperas.",
      "Cada desafío te prepara para una floración espectacular.",
      "Tu belleza única rompe con lo convencional."
    ],
    descripcionExtendida: "Las Huernias son suculentas que forman pequeños arbustos con tallos angulares y sin espinas. Son muy valoradas por sus flores, que a menudo son estrelladas, carnosas y con patrones intrincados o colores llamativos, aunque algunas pueden tener un aroma peculiar (para atraer polinizadores). Son relativamente fáciles de cuidar y se adaptan bien a climas cálidos y secos. Ideales para coleccionistas que buscan plantas con floraciones inusuales y gran resistencia.",
    imagenUrl: "fotos/huernia.jpg"
  },
  {
    key: "callisia-navicularis",
    nombre: "Callisia navicularis",
    signos: ["Cáncer", "Piscis", "Tauro"],
    vida: ["Protección", "Conexión"],
    elementos: ["Agua", "Tierra"],
    niveles: ["Emocional", "Físico"],
    short: "Hojas en forma de barco, se adapta y protege.",
    descripcion: "Simboliza la protección del hogar y la conexión con el entorno.",
    energia: "conexión, protección, adaptabilidad",
    arquetipos: [
      "Como un abrazo, te envuelve en seguridad y calma.",
      "En el viaje de la vida, tu hogar es tu ancla.",
      "La protección viene de la conexión profunda con tu esencia.",
      "Cada paso te lleva a un nuevo refugio seguro.",
      "Tu fuerza está en la conexión con lo que nutre tu alma.",
      "El camino se abre cuando te sientes seguro y enraizado.",
      "La calma te guía a través de las aguas turbulentas.",
      "Protege tu paz, es tu tesoro más valioso.",
      "Un viaje seguro comienza con la armonía interna.",
      "Tu ser es un barco que navega hacia la calma."
    ],
    descripcionExtendida: "La Callisia navicularis es una pequeña suculenta rastrera que se distingue por sus hojas carnosas y ovaladas dispuestas en forma de tejas o barcos a lo largo de sus tallos. Sus hojas son de color verde oscuro, a menudo con un tinte púrpura en los bordes o el envés, especialmente bajo luz solar intensa. Es ideal para macetas colgantes o como cobertura de suelo, y produce pequeñas flores rosadas en verano. Es de fácil cultivo y muy decorativa por su peculiar forma.",
    imagenUrl: "fotos/callisia-navicularis.jpg"
  },
  {
    key: "cactus-coral",
    nombre: "Cactus coral",
    signos: ["Piscis", "Cáncer", "Escorpio"],
    vida: ["Conexión", "Fluidez"],
    elementos: ["Agua"],
    niveles: ["Espiritual", "Emocional"],
    short: "Formas ondulantes, evoca el mar y la creatividad.",
    descripcion: "Representa la adaptabilidad, la conexión emocional y la creatividad fluida.",
    energia: "fluidez, adaptabilidad, creatividad",
    arquetipos: [
      "Tu creatividad fluye como las olas del mar, sin límites.",
      "La suavidad del coral esconde la fuerza de la creación.",
      "Conecta con la profundidad de tu ser, allí está tu verdad.",
      "El océano de la vida te invita a bailar con sus corrientes.",
      "Deja que tu intuición te guíe como las mareas del mar.",
      "La vida tiene sus propias formas, déjate moldear por ellas.",
      "Descubre la belleza en las formas inesperadas de la vida.",
      "Sumérgete en tus sueños, y deja que fluyan libremente.",
      "Como el coral, tu crecimiento es constante, aunque lento.",
      "La creatividad emerge de la calma de las profundidades."
    ],
    descripcionExtendida: "El Cactus Coral (Rhipsalis cereuscula) es una suculenta epífita que se caracteriza por sus tallos delgados y ramificados que se asemejan a pequeñas ramas de coral o cuentas. Sus segmentos verdes se engrosan hacia las puntas, dándole una textura única. Es ideal para macetas colgantes, creando un efecto cascada, y produce pequeñas flores blancas o amarillentas. Requiere sombra parcial y un poco más de humedad que otros cactus, siendo una planta de interior muy popular por su aspecto inusual y fácil cuidado.",
    imagenUrl: "fotos/cactus-coral.jpg"
  },
  {
    key: "madreperla",
    nombre: "Madreperla",
    signos: ["Tauro", "Virgo", "Capricornio"],
    vida: ["Crecimiento", "Paz"],
    elementos: ["Tierra", "Agua"],
    niveles: ["Físico", "Emocional"],
    short: "Roseta compacta, tonos perlados, crecimiento suave.",
    descripcion: "Simboliza la paz, el crecimiento constante y la belleza serena.",
    energia: "paz, crecimiento, armonía",
    arquetipos: [
      "Tu crecimiento silencioso es tu mayor fortaleza, no tu debilidad.",
      "La vida te entrega perlas de sabiduría en cada experiencia.",
      "El interior de tu ser es un tesoro de calma y brillo.",
      "Florece con la paciencia de la naturaleza, sin prisa.",
      "Tu paz interior es tu joya más preciada, cultívala.",
      "Cada paso te acerca a la armonía que buscas.",
      "La serenidad es el reflejo de tu alma en paz.",
      "Deja que tu luz interior brille con suavidad y constancia.",
      "La verdadera riqueza está en la tranquilidad de tu espíritu.",
      "Como la perla, tu belleza es fruto de la paciencia y el tiempo."
    ],
    descripcionExtendida: "La Graptopetalum paraguayense, conocida popularmente como Madreperla, es una suculenta que forma rosetas compactas de hojas carnosas, planas y de un distintivo color gris azulado a rosado-púrpura, que a menudo desarrollan un tono nacarado bajo la luz solar. Sus tallos crecen y se extienden, creando colonias densas. Es una planta extremadamente resistente y fácil de propagar, ideal para principiantes y para usar en jardines de rocas, macetas o arreglos mixtos.",
    imagenUrl: "fotos/madreperla.jpg"
  },
  {
    key: "mammillaria-vetula",
    nombre: "Mammillaria vetula",
    signos: ["Géminis", "Libra", "Acuario"],
    vida: ["Claridad", "Comunicación"],
    elementos: ["Aire"],
    niveles: ["Mental", "Espiritual"],
    short: "Cactus globular, espinas delicadas, purificador.",
    descripcion: "Representa la claridad de pensamiento, la protección sutil y la expansión de la sabiduría.",
    energia: "claridad, sabiduría, protección",
    arquetipos: [
      "Tu mente es un jardín de ideas claras y luminosas.",
      "Las palabras sabias crecen en el silencio de la contemplación.",
      "La verdad se revela en la sencillez de un pensamiento puro.",
      "Protege tu espacio mental, es tu santuario interior.",
      "La claridad te abre caminos que antes no veías.",
      "Sé como este cactus: fuerte por dentro, pero gentil por fuera.",
      "La sabiduría es como una espina: te protege y te ayuda a crecer.",
      "En cada idea, hay una semilla de crecimiento y evolución.",
      "La ligereza de tu ser te permite elevarte sobre las preocupaciones.",
      "El conocimiento florece donde hay espacio para la reflexión."
    ],
    descripcionExtendida: "La Mammillaria vetula es un pequeño cactus globular, que con el tiempo puede formar grupos. Se caracteriza por sus espinas finas y suaves, a menudo blancas o amarillentas, que cubren densamente su cuerpo verde. Produce pequeñas flores en forma de campana en tonos crema o rosa pálido alrededor de su corona. Es una especie de fácil cultivo, resistente y de crecimiento lento, perfecta para coleccionistas que aprecian la delicadeza y la forma compacta de los cactus mamilares.",
    imagenUrl: "fotos/mammillaria-vetula.jpg"
  },
  {
    key: "mammillaria-prolifera",
    nombre: "Mammillaria prolifera",
    signos: ["Leo", "Géminis", "Sagitario"],
    vida: ["Alegría", "Abundancia"],
    elementos: ["Fuego", "Aire"],
    niveles: ["Físico", "Mental"],
    short: "Multiplica la alegría, flores y frutos abundantes.",
    descripcion: "Representa la proliferación de la alegría, la vitalidad y la conexión con la vida a tu alrededor.",
    energia: "alegría, renovación, vitalidad",
    arquetipos: [
      "Un estallido de energía en miniatura, trayendo alegría a cada rincón.",
      "Resistente y vital, te recuerda que la vida florece en los lugares más inesperados.",
      "Guarda en silencio la fuerza que crece sin ser vista.",
      "Resiste con dulzura: tu suavidad es tu escudo.",
      "No necesitas mostrar espinas para proteger tu esencia.",
      "La alegría sencilla multiplica la abundancia.",
      "Expande tu energía como el sol de la mañana.",
      "Cada hoja es un pequeño milagro de perseverancia.",
      "Vitalidad solar, alegría contagiosa.",
      "La ligereza del juego hace más fácil el camino."
    ],
    descripcionExtendida: "La Mammillaria prolifera es un cactus de bajo crecimiento que forma densos grupos con sus pequeños tallos globulares o cilíndricos. Se caracteriza por sus espinas radiales blancas y suaves que cubren casi por completo la planta, dándole un aspecto lanudo. Produce abundantes flores pequeñas, de color crema a rosado, seguidas de frutos rojos brillantes que permanecen en la planta durante mucho tiempo. Es muy fácil de propagar y de cuidar, ideal para principiantes y para añadir textura a una colección de cactus.",
    imagenUrl: "fotos/mammillaria-prolifera.jpg"
  },
  {
    key: "echeveria-elegans",
    nombre: "Echeveria elegans",
    signos: ["Libra", "Tauro", "Piscis"],
    vida: ["Belleza", "Armonía", "Gracia"],
    elementos: ["Tierra", "Agua"],
    niveles: ["Emocional", "Espiritual"],
    short: "Roseta perfecta, belleza elegante y duradera.",
    descripcion: "Simboliza la gracia, la elegancia, la armonía y la belleza en su forma más pura.",
    energia: "armonía, belleza, paz",
    arquetipos: [
      "Tu belleza interior se refleja en la armonía de tu ser.",
      "La gracia está en la forma en que te despliegas ante el mundo.",
      "Cada pétalo de tu alma es un acto de belleza pura.",
      "La elegancia es un estado del ser, no una forma de vestir.",
      "Florece con la suavidad de un pétalo, la fuerza de una roca.",
      "Encuentra la paz en la simetría y el orden de la naturaleza.",
      "La armonía nace de la aceptación de tu propia perfección.",
      "Tu presencia irradia calma y belleza a tu alrededor.",
      "Sé como esta Echeveria: perfecta en tu simplicidad.",
      "La belleza verdadera es aquella que nutre el alma."
    ],
    descripcionExtendida: "La Echeveria elegans, también conocida como 'Rosa de Mármol' o 'Perla de Núremberg', es una de las suculentas más populares y cultivadas. Forma rosetas compactas y simétricas de hojas carnosas de color verde pálido a azul-grisáceo, a menudo con puntas rosadas. Produce tallos florales altos con pequeñas flores rosadas o rojizas en primavera. Es extremadamente fácil de cuidar, se propaga fácilmente y es ideal para principiantes, jardines de rocas y arreglos.",
    imagenUrl: "fotos/echeveria-elegans.jpg"
  },
  {
    key: "crassula-fragilis",
    nombre: "Crassula expansa fragilis",
    signos: ["Piscis", "Cáncer", "Libra"],
    vida: ["Conexión", "Adaptabilidad"],
    elementos: ["Agua", "Aire"],
    niveles: ["Emocional", "Espiritual"],
    short: "Hojas delicadas, crecimiento en cascada, fragilidad hermosa.",
    descripcion: "Simboliza la delicadeza, la adaptabilidad y la interconexión de la vida.",
    energia: "adaptabilidad, fluidez, crecimiento",
    arquetipos: [
      "La verdadera fuerza reside en la capacidad de doblarse sin romperse.",
      "La belleza está en la imperfección, en lo que es frágil y real.",
      "Tus conexiones son tus raíces, te nutren y te sostienen.",
      "Crece en cada dirección, explorando nuevas formas de ser.",
      "En la adaptabilidad está la clave para florecer en cualquier entorno.",
      "La vida teje redes de conexión invisibles y poderosas.",
      "La fragilidad es un recordatorio de la belleza de la vida.",
      "Fluye con el cambio, sé flexible como el agua que te nutre.",
      "En cada quiebre, hay una oportunidad para un nuevo crecimiento.",
      "Tu esencia es adaptable, lista para abrazar nuevas formas."
    ],
    descripcionExtendida: "La Crassula expansa fragilis es una suculenta de bajo crecimiento con tallos delgados y ramificados que se extienden formando una cubierta densa. Sus pequeñas hojas carnosas son de color verde brillante y se disponen en pares opuestos a lo largo del tallo. Es apreciada por su rápido crecimiento y su capacidad para crear un efecto de cascada en macetas colgantes o como cobertura de suelo. Aunque su nombre sugiere 'fragilidad', es una planta robusta y fácil de cuidar, ideal para llenar espacios rápidamente con su textura fina.",
    imagenUrl: "fotos/crassula-fragilis.jpg"
  },
  {
    key: "opuntia-monacantha-monstruosa",
    nombre: "Opuntia monacantha monstruosa",
    signos: ["Aries", "Escorpio", "Capricornio"],
    vida: ["Transformación", "Fuerza"],
    elementos: ["Fuego", "Tierra"],
    niveles: ["Físico", "Mental"],
    short: "Formas únicas y mutantes, fuerte y adaptativa.",
    descripcion: "Representa la individualidad, la transformación constante y la fuerza para romper moldes.",
    energia: "transformación, fuerza, unicidad",
    arquetipos: [
      "Tu singularidad te hace imparable, abraza tu propia forma.",
      "Rompe los moldes, tu poder reside en ser auténtico.",
      "La vida te invita a mutar, a transformarte sin miedo.",
      "En tu fuerza está la clave para lo que parece imposible.",
      "Sé audaz, sé diferente, sé inconfundiblemente tú.",
      "Cada espina es un recordatorio de tu capacidad de defensa.",
      "La transformación es tu arte, tu lienzo es tu vida.",
      "Tu espíritu es un laberinto de posibilidades y crecimiento.",
      "La creatividad más pura nace de la libertad de ser.",
      "Eres una obra de arte en constante evolución."
    ],
    descripcionExtendida: "La Opuntia monacantha monstruosa, también conocida como 'Monstrose Prickly Pear' o 'Opuntia Coral', es una variedad inusual de Opuntia que desarrolla tallos de formas irregulares y onduladas, a menudo con una apariencia crestada o abultada, dándole un aspecto arquitectónico y escultórico. Sus espinas son escasas o ausentes en algunas áreas. Produce flores amarillas en verano. Es una suculenta de crecimiento robusto y fácil cuidado, ideal para quienes buscan una planta con una forma escultural y llamativa.",
    imagenUrl: "fotos/opuntia-monacantha-monstruosa.jpg"
  },
  {
    key: "senecio-articulatus",
    nombre: "Senecio articulatus",
    signos: ["Acuario", "Géminis", "Virgo"],
    vida: ["Claridad", "Renovación"],
    elementos: ["Aire"],
    niveles: ["Mental", "Espiritual"],
    short: "Tallos segmentados, purifica y renueva.",
    descripcion: "Simboliza la claridad, la purificación mental y la capacidad de renovación.",
    energia: "purificación, renovación, claridad",
    arquetipos: [
      "Cada ciclo trae una nueva oportunidad para purificar tu mente.",
      "La claridad de tus pensamientos es tu mayor poder.",
      "Libera lo que no te sirve, haz espacio para lo nuevo.",
      "Tu mente es un jardín que necesita ser podado con amor.",
      "La renovación es un proceso constante, no un destino.",
      "En la sencillez de la naturaleza, encontrarás la verdad.",
      "Como el tallo que se desprende, suelta lo que te pesa.",
      "Respira profundo, y deja que el aire purifique tu alma.",
      "La sabiduría reside en saber cuándo soltar y renovarse.",
      "La frescura de tu espíritu es tu guía en el camino."
    ],
    descripcionExtendida: "El Senecio articulatus, conocido comúnmente como 'Planta del Incienso' o 'Hot Dog Cactus', es una suculenta arbustiva con tallos carnosos y segmentados que parecen salchichas o 'articulaciones'. Sus tallos son de color verde grisáceo y, en condiciones de estrés, pueden desarrollar tonos rosados o púrpuras. En invierno, cuando la planta está inactiva, sus hojas caen y los tallos quedan expuestos, mostrando su forma única. Produce pequeñas flores blancas o amarillentas. Es una planta fácil de cuidar y muy distintiva por su morfología.",
    imagenUrl: "fotos/senecio-articulatus.jpg"
  },
  {
    key: "sedum-rubrotinctum-jelly-beans",
    nombre: "Sedum Rubrotinctum 'Jelly Beans'",
    signos: ["Aries", "Leo", "Sagitario"],
    vida: ["Alegría", "Vitalidad"],
    elementos: ["Fuego", "Tierra"],
    niveles: ["Físico", "Emocional"],
    short: "Hojas vibrantes, llenas de color y energía.",
    descripcion: "Representa la alegría vibrante, la vitalidad y la dulzura de la vida.",
    energia: "alegría, vitalidad, optimismo",
    arquetipos: [
      "Tu vida es un jardín de colores vibrantes, disfrútalos.",
      "La dulzura de tu espíritu es un regalo para el mundo.",
      "Cada día es una nueva oportunidad para brillar con alegría.",
      "El sol pinta tu alma con tonos de felicidad y energía.",
      "La vitalidad de tu ser contagia a todos a tu alrededor.",
      "La vida es un festín de pequeños placeres, disfrútalos.",
      "Sé una chispa de alegría en el mundo, como un fuego fatuo.",
      "Tu energía es contagiosa, irradia felicidad en cada paso.",
      "La felicidad se cultiva con pequeños actos de amor y color.",
      "La vida es un dulce manjar, tómate tu tiempo para saborearla."
    ],
    descripcionExtendida: "El Sedum Rubrotinctum, comúnmente conocido como 'Jelly Beans' o 'Punta de Fuego', es una suculenta muy popular por sus hojas carnosas en forma de frijol que se tiñen de un vibrante rojo brillante bajo el sol, especialmente en los bordes y las puntas. Sus tallos rastreros forman densas matas, lo que la hace ideal para cobertura de suelo, macetas colgantes o como acento en arreglos. En primavera, produce pequeñas flores amarillas. Es extremadamente fácil de cuidar y una excelente opción para principiantes por su resistencia y colorido.",
    imagenUrl: "fotos/sedum-rubrotinctum-jelly-beans.jpg"
  },
  {
    key: "sedum-luteoviride",
    nombre: "Sedum Luteoviride",
    signos: ["Virgo", "Tauro", "Capricornio"],
    vida: ["Estabilidad", "Crecimiento"],
    elementos: ["Tierra"],
    niveles: ["Físico", "Mental"],
    short: "Hojas verdes-amarillas, crecimiento constante y fresco.",
    descripcion: "Simboliza el crecimiento constante, la estabilidad y la frescura renovadora.",
    energia: "frescura, estabilidad, crecimiento",
    arquetipos: [
      "Tu crecimiento es constante y silencioso, pero poderoso.",
      "La frescura de la naturaleza te nutre y te revitaliza.",
      "En la estabilidad de la tierra, encuentras tu fundamento.",
      "Cada hoja es un paso más en tu camino de crecimiento.",
      "La vida te invita a arraigarte, a crecer con propósito.",
      "La sencillez de la naturaleza te enseña la verdadera riqueza.",
      "La estabilidad de tu ser te permite florecer en cualquier estación.",
      "Tu energía es constante, nutriendo todo a tu alrededor.",
      "En la calma de tu ser, reside una fuerza inquebrantable.",
      "La paz interior te guía hacia un crecimiento pleno y constante."
    ],
    descripcionExtendida: "El Sedum Luteoviride es una atractiva suculenta que forma rosetas de hojas lanceoladas y carnosas, de un distintivo color verde amarillento o chartreuse. Sus hojas a menudo se agrupan densamente a lo largo de tallos que pueden crecer erguidos o ligeramente decumbentes. Esta planta es ideal para añadir un toque de color brillante y textura a jardines de rocas, macetas o arreglos mixtos de suculentas. Es de fácil cuidado y puede producir pequeñas flores amarillas en verano.",
    imagenUrl: "fotos/sedum-luteoviride.jpg"
  },
  {
    key: "sedum-clavatum",
    nombre: "Sedum clavatum",
    signos: ["Tauro", "Libra", "Piscis"],
    vida: ["Paz", "Armonía"],
    elementos: ["Tierra", "Agua"],
    niveles: ["Emocional", "Espiritual"],
    short: "Hojas en forma de mazo, calma y equilibrio.",
    descripcion: "Representa la paz interior, la armonía y la belleza en la simplicidad.",
    energia: "paz, armonía, equilibrio",
    arquetipos: [
      "En la simplicidad de la forma, encuentras la paz.",
      "La calma es el estado natural de tu ser interior.",
      "Cada hoja es una promesa de serenidad y equilibrio.",
      "Tu espíritu se despliega en armonía con el universo.",
      "La belleza reside en la aceptación de tu propia forma.",
      "La paz se construye paso a paso, con cada respiración.",
      "Como un mazo de calma, esta planta te invita a la quietud.",
      "En el silencio, encuentras las respuestas que buscas.",
      "La verdadera fuerza está en la suavidad de la armonía.",
      "La simplicidad es el camino hacia la paz duradera."
    ],
    descripcionExtendida: "El Sedum clavatum es una suculenta que forma rosetas compactas de hojas carnosas en forma de mazo, de color verde pálido a azul-grisáceo, con las puntas a menudo teñidas de rosa o rojo bajo el sol intenso. Sus rosetas crecen en tallos que pueden ramificarse y formar matas densas. Produce pequeñas flores blancas en primavera. Es una planta muy ornamental y fácil de cuidar, ideal para jardines de rocas, macetas o como un toque delicado.",
    imagenUrl: "fotos/sedum-clavatum.jpg"
  },
  {
    key: "pachyphytum-compactum",
    nombre: "Pachyphytum compactum",
    signos: ["Escorpio", "Capricornio", "Acuario"],
    vida: ["Estructura", "Resistencia"],
    elementos: ["Tierra"],
    niveles: ["Físico", "Mental"],
    short: "Hojas geométricas, resistente y fuerte.",
    descripcion: "Simboliza la estructura interna, la resistencia y la belleza de la forma.",
    energia: "fuerza, estructura, resistencia",
    arquetipos: [
      "Tu fuerza está en la solidez de tu ser, en tu esencia.",
      "La resistencia te permite superar cualquier desafío.",
      "Construye tu vida con la estructura de un propósito claro.",
      "La belleza reside en la precisión de cada forma.",
      "Cada curva es una fortaleza, cada línea una dirección.",
      "Como una joya tallada, tu valor es inmutable.",
      "En la firmeza de tu ser, encuentras la verdadera libertad.",
      "Tu espíritu es un cristal, resistente y lleno de luz.",
      "La vida te invita a pulir tus talentos, a mostrar tu brillo.",
      "La perfección está en los detalles, en la dedicación de tu arte."
    ],
    descripcionExtendida: "El Pachyphytum compactum es una suculenta muy distintiva que forma rosetas densas de hojas cilíndricas y carnosas con facetas o 'cortes' que le dan un aspecto geométrico único, como si hubieran sido esculpidas. Sus hojas son de color verde grisáceo a púrpura-grisáceo, a menudo con una capa pruinosa. Produce pequeñas flores en tonos rojizos o anaranjados en tallos largos. Es una planta de crecimiento lento, ideal para coleccionistas que aprecian las formas inusuales y la resistencia.",
    imagenUrl: "fotos/pachyphytum-compactum.jpg"
  },
  {
    key: "opuntia-microdasys",
    nombre: "Opuntia microdasys",
    signos: ["Aries", "Leo", "Géminis"],
    vida: ["Protección", "Alegría"],
    elementos: ["Fuego", "Aire"],
    niveles: ["Físico", "Emocional"],
    short: "Cactus sin espinas, puntitos de alegría.",
    descripcion: "Representa la protección sutil, la alegría y la adaptación sin agresión.",
    energia: "protección, alegría, suavidad",
    arquetipos: [
      "Tu suavidad es tu fuerza, tu dulzura tu escudo.",
      "La alegría reside en los pequeños detalles de la vida.",
      "Protege tu corazón con la delicadeza de una caricia.",
      "No necesitas mostrar espinas para ser fuerte y seguro.",
      "Tu presencia irradia luz, sin necesidad de imponerse.",
      "La sabiduría está en la dulzura de tu interacción.",
      "Los pequeños puntos de tu vida son tus mayores fortalezas.",
      "La alegría te protege, te envuelve en una burbuja de paz.",
      "Tu energía es como un abrazo suave, lleno de luz.",
      "La belleza de tu ser es discreta, pero inconfundible."
    ],
    descripcionExtendida: "La Opuntia microdasys, conocida popularmente como 'Orejas de Conejo' o 'Cactus de lunares', es un cactus muy popular por sus tallos planos y ovalados que forman 'raquetas' con areolas cubiertas de gloquidios (espinas muy finas y pegadizas) que parecen lunares. No tiene espinas largas y afiladas, lo que la hace visualmente más amigable. Produce flores amarillas en verano. Es fácil de cuidar y una excelente opción para principiantes por su forma divertida y su resistencia.",
    imagenUrl: "fotos/opuntia-microdasys.jpg"
  },
  {
    key: "haworthia-cuspidata",
    nombre: "Haworthia Cuspidata",
    signos: ["Capricornio", "Virgo", "Tauro"],
    vida: ["Foco", "Conexión"],
    elementos: ["Tierra"],
    niveles: ["Mental", "Espiritual"],
    short: "Hojas translúcidas, foco y visión interior.",
    descripcion: "Simboliza la claridad de visión, la intuición y la conexión con la verdad interior.",
    energia: "foco, intuición, claridad",
    arquetipos: [
      "Tu visión interior es tu guía más certera.",
      "En la transparencia de tu ser, reside la verdad.",
      "La claridad de tu mente es un faro en la oscuridad.",
      "Conecta con la sabiduría que está dentro de ti.",
      "Cada capa de tu ser revela una nueva profundidad.",
      "El foco en lo esencial te abre nuevas perspectivas.",
      "La intuición es tu brújula, confía en ella.",
      "La luz atraviesa tu ser, revelando tu verdadera esencia.",
      "En cada detalle, hay una lección de claridad y verdad.",
      "Tu fuerza está en la calma de tu observación."
    ],
    descripcionExtendida: "La Haworthia cuspidata es una pequeña suculenta que forma rosetas compactas de hojas carnosas y triangulares, de color verde translúcido. Sus hojas son a menudo más anchas en la base y se estrechan hacia una punta afilada ('cuspidata' significa 'con punta'). Es una planta de crecimiento lento, ideal para interiores o jardines de sombra, y es muy apreciada por su aspecto similar a una joya y su resistencia. Produce pequeñas flores blancas en tallos altos.",
    imagenUrl: "fotos/haworthia-cuspidata.jpg"
  },
  {
    key: "gasteria-pillansii",
    nombre: "Gasteria pillansii",
    signos: ["Capricornio", "Escorpio", "Cáncer"],
    vida: ["Resistencia", "Estabilidad"],
    elementos: ["Tierra", "Agua"],
    niveles: ["Físico", "Emocional"],
    short: "Hojas rugosas, fuerza y adaptabilidad.",
    descripcion: "Representa la fuerza oculta, la resistencia y la adaptabilidad profunda.",
    energia: "resistencia, protección, adaptabilidad",
    arquetipos: [
      "Tu fuerza silenciosa es tu mayor poder, no la subestimes.",
      "La resistencia se forja en los desafíos de la vida.",
      "Protege tu espacio interior con la solidez de la roca.",
      "La adaptabilidad te permite florecer en cualquier terreno.",
      "Tu esencia es robusta, capaz de soportar cualquier tempestad.",
      "La sabiduría reside en la capacidad de mantenerse firme.",
      "Como la piedra, tu fuerza es inquebrantable y duradera.",
      "Tu espíritu se nutre de la conexión con lo profundo.",
      "En cada dificultad, hay una oportunidad para arraigarte más.",
      "La verdadera protección viene de la confianza en ti mismo."
    ],
    descripcionExtendida: "La Gasteria pillansii es una suculenta de crecimiento lento que forma rosetas sin tallo de hojas gruesas, carnosas y rígidas, a menudo con una textura rugosa o verrugosa y de color verde oscuro. Sus hojas se disponen en dos hileras opuestas (distichous), dándole una forma aplanada y distintiva. Produce flores tubulares de color rosado a anaranjado en tallos altos. Es una planta muy resistente y de fácil cuidado, ideal para interiores o jardines de sombra.",
    imagenUrl: "fotos/gasteria-pillansii.jpg"
  },
  {
    key: "echeveria-setosa",
    nombre: "Echeveria Setosa",
    signos: ["Virgo", "Tauro", "Capricornio"],
    vida: ["Pureza", "Confort"],
    elementos: ["Tierra"],
    niveles: ["Físico", "Emocional"],
    short: "Hojas peludas, suavidad y protección.",
    descripcion: "Simboliza la pureza, el confort, la protección y la conexión con la naturaleza.",
    energia: "calma, confort, pureza",
    arquetipos: [
      "La suavidad de tu espíritu te envuelve en un abrazo de paz.",
      "La pureza de tu intención te guía en cada paso.",
      "Tu confort es tu santuario, nútrelo con amor.",
      "Cada fibra de tu ser irradia una energía de calma.",
      "La vida te invita a sentir la delicadeza de la existencia.",
      "La protección es un manto de amor que te envuelve siempre.",
      "En la sencillez de la naturaleza, encuentras tu verdadero ser.",
      "Tu corazón es un lugar de pureza y de paz infinita.",
      "La calma es el lenguaje de tu alma en reposo.",
      "La belleza reside en la suavidad de tu presencia."
    ],
    descripcionExtendida: "La Echeveria setosa, conocida como 'Echeveria peluda' o 'Gallina y polluelos peluda', es una suculenta que forma rosetas compactas de hojas carnosas de color verde grisáceo cubiertas de pequeños pelos blancos que le dan una textura suave y aterciopelada. Estos pelos le dan un aspecto escarchado y también la protegen del sol intenso. Produce tallos florales con pequeñas flores rojas o anaranjadas en primavera-verano. Es fácil de cuidar y muy atractiva por su textura única.",
    imagenUrl: "fotos/echeveria-setosa.jpg"
  },
  {
    key: "crassula-pellucida",
    nombre: "Crassula Pellucida",
    signos: ["Cáncer", "Piscis", "Libra"],
    vida: ["Conexión", "Crecimiento"],
    elementos: ["Agua", "Aire"],
    niveles: ["Emocional", "Espiritual"],
    short: "Hojas translúcidas, crecimiento y fluidez.",
    descripcion: "Simboliza la fluidez, la conexión emocional y la adaptabilidad constante.",
    energia: "fluidez, conexión, adaptabilidad",
    arquetipos: [
      "Tu vida fluye como un río, abrazando cada curva del camino.",
      "La transparencia de tu ser revela tu verdadera belleza.",
      "Conecta con la corriente de la vida, déjate llevar por ella.",
      "Cada hoja es un reflejo de la luz que te atraviesa.",
      "La adaptabilidad es tu superpoder, te permite crecer en todo.",
      "En cada conexión, hay una oportunidad para florecer.",
      "Tu espíritu es un cristal, receptivo a las energías del mundo.",
      "La fluidez te libera de las ataduras, te permite ser tú.",
      "La vida te invita a ser transparente, a mostrar tu esencia.",
      "La belleza de tu ser está en la forma en que te adaptas al cambio."
    ],
    descripcionExtendida: "La Crassula pellucida es una suculenta rastrera o colgante con tallos delgados y hojas pequeñas, carnosas y translúcidas, de color verde brillante que pueden desarrollar tonos rojizos en los bordes con la luz solar. Es conocida por su rápido crecimiento y su capacidad para formar densas cubiertas o cascadas. Produce pequeñas flores blancas o rosadas. Es una planta muy versátil y fácil de cuidar, ideal para macetas colgantes, terrarios o como cobertura de suelo.",
    imagenUrl: "fotos/crassula-pellucida.jpg"
  },
  {
    key: "corpuscularia-lehmannii",
    nombre: "Corpuscularia lehmannii",
    signos: ["Capricornio", "Escorpio", "Virgo"],
    vida: ["Estabilidad", "Resistencia"],
    elementos: ["Tierra"],
    niveles: ["Físico", "Mental"],
    short: "Hojas gruesas, resistencia y durabilidad.",
    descripcion: "Representa la resistencia, la fortaleza y la capacidad de anclarse en la realidad.",
    energia: "resistencia, anclaje, fortaleza",
    arquetipos: [
      "Tu fortaleza interior es inquebrantable, como una roca.",
      "La resistencia te permite superar cualquier tormenta.",
      "Ancla tus raíces en la tierra, y sé firme en tu propósito.",
      "Cada hoja es un recordatorio de tu capacidad de soportar.",
      "La sabiduría reside en la estabilidad de tu ser.",
      "Tu cuerpo es tu templo, cuídalo con amor y resistencia.",
      "La vida te invita a construir bases sólidas y duraderas.",
      "En la firmeza de tu ser, encuentras la verdadera paz.",
      "La perseverancia es la clave para alcanzar tus metas.",
      "Tu espíritu es un árbol, arraigado y fuerte, capaz de crecer."
    ],
    descripcionExtendida: "La Corpuscularia lehmannii es una suculenta de crecimiento bajo que forma densas matas de hojas carnosas, triangulares y de color verde azulado a grisáceo. Sus hojas son gruesas y se agrupan en tallos cortos, dándole un aspecto compacto y denso. Produce pequeñas flores amarillas brillantes que se abren con el sol. Es una planta muy resistente y fácil de cuidar, ideal para jardines de rocas, macetas o como cobertura de suelo, especialmente en climas secos.",
    imagenUrl: "fotos/corpuscularia-lehmannii.jpg"
  },
    {
    key: "sedeveria-maialen",
    nombre: "Sedeveria 'Maialen'",
    signos: ["Piscis", "Cáncer", "Libra"],
    vida: ["Calma", "Intuición"],
    elementos: ["Agua", "Tierra"],
    niveles: ["Emocional", "Espiritual"],
    short: "Hojas suaves, roseta compacta, tranquilizante.",
    descripcion: "Aporta calma, facilita la intuición y nutre la sensibilidad.",
    energia: "calma, intuición, sanación",
    arquetipos: [
      "La suavidad de la vida te acuna, trayendo calma a tu ser.",
      "Escucha la voz de tu intuición, te guiará con sabiduría.",
      "El agua de la vida fluye a través de ti, sanando y purificando.",
      "En la quietud, encontrarás las respuestas que buscas.",
      "Tu sensibilidad es un don, te conecta con el universo.",
      "La paz te envuelve, trayendo serenidad a tu corazón.",
      "Como la luna, tu intuición brilla en la oscuridad.",
      "La armonía se construye desde adentro hacia afuera.",
      "Permite que la calma te guíe hacia la sanación.",
      "Tu espíritu es un remanso de paz, un santuario de luz."
    ],
    descripcionExtendida: "La Sedeveria 'Maialen' es un híbrido intergenérico que combina características de Sedum y Echeveria, formando rosetas compactas de hojas carnosas, ovaladas y de color verde pálido, a menudo con un suave tinte rosado en los bordes. Es una planta de crecimiento bajo, ideal para macetas y arreglos de suculentas, apreciada por su aspecto delicado y su fácil cultivo. Produce pequeñas flores amarillas en tallos altos.",
    imagenUrl: "fotos/sedeveria-maialen.jpg"
  },
  {
    key: "kalanchoe-tomentosa",
    nombre: "Kalanchoe tomentosa (Orejas de Conejo)",
    signos: ["Tauro", "Virgo", "Cáncer"],
    vida: ["Confort", "Protección"],
    elementos: ["Tierra", "Agua"],
    niveles: ["Físico", "Emocional"],
    short: "Hojas peludas, suave y protectora, reconfortante.",
    descripcion: "Ofrece confort, protección y un suave abrazo en momentos de vulnerabilidad.",
    energia: "confort, protección, seguridad",
    arquetipos: [
      "La suavidad te envuelve, protegiéndote con ternura.",
      "Tu piel es tu armadura, pero tu corazón es tu hogar.",
      "El abrazo de la vida te ofrece seguridad y calma.",
      "En la protección de tu espacio, encuentras la paz.",
      "Permite que la suavidad te guíe a un refugio seguro.",
      "La vida te susurra dulzura, escúchala con el alma.",
      "Tu esencia es como un algodón, pura y reconfortante.",
      "El calor del hogar te envuelve, disipando las preocupaciones.",
      "Sé tu propio refugio, tu propio lugar seguro.",
      "La dulzura es una forma de fuerza, una caricia al alma."
    ],
    descripcionExtendida: "El Kalanchoe tomentosa, popularmente conocido como 'Orejas de Conejo' o 'Planta Panda', es una suculenta muy distintiva por sus hojas gruesas, ovaladas y cubiertas de una densa capa de vellosidades plateadas o grisáceas que le dan un aspecto suave y aterciopelado. Los bordes de las hojas a menudo están marcados con manchas marrones o rojizas. Es una planta de crecimiento lento a moderado, ideal para interiores y es apreciada por su textura única y su fácil cuidado.",
    imagenUrl: "fotos/kalanchoe-tomentosa.jpg"
  },
  {
    key: "gasteria-verrucosa",
    nombre: "Gasteria verrucosa (Lengua de Vaca)",
    signos: ["Capricornio", "Escorpio", "Virgo"],
    vida: ["Resistencia", "Autenticidad"],
    elementos: ["Tierra"],
    niveles: ["Físico", "Mental"],
    short: "Hojas con verrugas, robusta, autenticidad.",
    descripcion: "Fomenta la autenticidad, la resistencia y la conexión con lo real.",
    energia: "resistencia, autenticidad, anclaje",
    arquetipos: [
      "Tu autenticidad es tu mayor fuerza, no la disfraces.",
      "La textura de tu vida te hace único y real.",
      "En cada cicatriz, hay una historia de resistencia y verdad.",
      "Ancla tus pies en la tierra, tu verdad es tu refugio.",
      "La resistencia se construye con la aceptación de lo que eres.",
      "Tu fuerza no reside en ser suave, sino en ser genuino.",
      "Cada imperfección es una marca de tu belleza única.",
      "Sé valiente para mostrar tus verdaderas texturas.",
      "La vida te invita a ser crudo, real y profundamente tú.",
      "La verdad está en lo que sientes, no en lo que aparentas."
    ],
    descripcionExtendida: "La Gasteria verrucosa, también conocida como 'Lengua de Vaca', es una suculenta que forma rosetas sin tallo de hojas gruesas, alargadas y de color verde oscuro, cubiertas con numerosas protuberancias blancas ('verrugas') que le dan una textura áspera y distintiva. Sus hojas se disponen en dos hileras opuestas. Produce flores tubulares de color rosado a anaranjado en tallos largos. Es una planta muy resistente y de fácil cuidado, ideal para interiores o jardines de sombra.",
    imagenUrl: "fotos/gasteria-verrucosa.jpg"
  }
];